export const CTP_ORDER_CHANGE_SUBSCRIPTION_KEY =
  'CTP_ORDER_CHANGE_SUBSCRIPTION_KEY';
export const CTP_EXTENSION_BASE_URL = 'CTP_EXTENSION_BASE_URL';
export const CTP_TAX_CALCULATOR_EXTENSION_KEY = 'ctpTaxCalculatorExtension';
